# Experimental!
~ "git: github.com/amatgil/steal-gift" ~ AoCGet

~ "git: github.com/Omnikar/uiua-plot" ~ Data Plot
# ====== INPUTS ======
I ← AoCGet 2025 9
$ 7,1
$ 11,1
$ 11,7
$ 9,7
$ 9,5
$ 2,5
$ 2,3
$ 7,3
Sample ←

Simp  ← ◴⊂ ∩⌟(▽⊸⧋(/∨=))⊸⊃/↧/↥ # Fast and wrong
Part₁ ← /↥♭˙⊞(/×+₁⌵-) ⊜(⊜⋕⊸≠@,)⊸≠@\n
Disp  ← ⌝↘¯⟜⌝↘2_2 °⊚
Disp  ← &fwa"/tmp/plot"img"png" Plot Data ⁅÷₁₀₀₀

I
⊜(⊜⋕⊸≠@,)⊸≠@\n
Disp

# /◇⊂⧈(□ /⊂ ⧋+⟜(⇡-) ⊙+₁ ⍜□₂⍆) ⊂⟜⊢

# >₀°⊚
# # ≡₀(↯3)
# # ⍜(⊡8_4|⋅0_1_0)
# ⤸1
# ⌝↘¯⟜⌝↘2_2
# &ims
