[package]
name = "default-file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
get_aoc_input = { path = "../get_aoc_input" }
tokio = "1.23.0"
