# Experimental!
~ "git: github.com/amatgil/steal-gift" ~ AoCGet

# ====== INPUTS ======
Input ← AoCGet 2024 ->Day<-

# ====== Shared ======

# ====== PART 1 ======
Part₁ ← 3◌

# ====== PART 2 ======
Part₂ ← 4◌

# ====== TESTS =======
# Input here
⍤⤙≍ "testout1" Part₁
# ⍤⤙≍ "testout2" Part₂

# ======== RUNNING ========
# $"Part one solution is: '_'" Part₁ Input

# $"Part two solution is: '_'" Part₂ Input
